### ISSUE TITLE
Installer issues - new purchase

### ISSUE THREAD

**Issue by stavoxnetworks** [crystalidea/anytoiso#13]
I purchased AnyToISO today and as the install finished, I received an error stating that several of the QT components were missing. I was under the impression that the QT components (QT5core.dll, QT5Network.dll etc...) were installed as the product installs. This is true of MalwareBytes and several other QT based apps I use. The installer (anytoiso.exe) I used was from the link in the email purchase confirmation. My OS is Windows 10 build 1709. I have attached screenshots from the install and the state of the "Program Files(x86)" folder directly following the install.

<img width="306" alt="2018-06-18 13_37_25-c__program files x86 _anytoiso" src="https://user-images.githubusercontent.com/27533789/41580636-9239d7ea-7369-11e8-88d9-2a9bc20f9151.png">

<img width="510" alt="program files folder directly after installation" src="https://user-images.githubusercontent.com/27533789/41580578-5fca166c-7369-11e8-87d3-5826c4fba94c.png">

**Comment by kleuter** [comment]
We apologize for the inconvenience, we fixed the setup, please re-download
https://www.crystalidea.com/downloads/anytoiso_setup.exe
