### ISSUE TITLE
Invalid XAR archive (magic mismatch)

### ISSUE THREAD

**Issue by Rost45482** [crystalidea/anytoiso#37]

**Comment by Rost45482** [comment]
![image](https://user-images.githubusercontent.com/79542519/108902498-39c8d100-762d-11eb-8256-89815802c6f4.png)

**Comment by kleuter** [comment]
Any chance to download this file to check?

**Comment by Rost45482** [comment]
Yes

**Comment by Rost45482** [comment]
https://ros.torrent-4igruha.ru/1183-ea-sports-ufc-3.html

**Comment by kleuter** [comment]
The file isn't a valid XAR
