### ISSUE TITLE
Explorer.exe crashes because of AnyToISO shell extension

### ISSUE THREAD

**Issue by kleuter** [crystalidea/anytoiso#7]
Unfortunately not currently able to reproduce. Video from a customer is attached.
[AnyToISO_1.zip](https://github.com/crystalidea/anytoiso/files/1782637/AnyToISO_1.zip)

**Comment by kleuter** [comment]
I have investigated my Problem and have this result.
The interaction with anyToISO and NVIDIA crashes the Explorer.
Both alone work very fine.
![sshot-2018-03-07- 13-56-20](https://user-images.githubusercontent.com/2600624/37093348-5537853c-220f-11e8-939a-e6a0292cf4dc.png)
[EventViewer.txt](https://github.com/crystalidea/anytoiso/files/1789194/EventViewer.txt)

**Comment by kleuter** [comment]
Unfortunately I wasn't able to reproduce it.

**Comment by gencer** [comment]
@kleuter, I have the exact problem. If I disable NVIDIA (2 entries) within ShellExView, then it works.

**Comment by gencer** [comment]
Update: @kleuter, these two needs to be disabled:

![image](https://user-images.githubusercontent.com/1711576/42766354-ef016faa-8922-11e8-872e-b904a8ee16f1.png)

I see only one in your screenshot.

**Comment by kleuter** [comment]
Ok! I reproduced the crash multiple times. According to system error logs, the crash happens in the 
C:\WINDOWS\SYSTEM32\explorerframe.dll
module. And it still happens if AnyToISO extension is __not__ installed! The crash doesn't happen if mentioned nvidia context menu extensions are removed.
